### ISSUE TITLE
Test result

### ISSUE THREAD

**Issue by Volodymyr233** [jmliu206/LIC_TCM#1]
Hello, I was wondering if you could give the PSNR and BPP values of your method on common test sets (e.g. Kodak, Tecnick, CLIC) as I would like to compare with your method.

**Comment by jmliu206** [comment]
Thank you for your interest in our work. The detailed R&D data is as follows:
## Kodak ##
PSNR = [30.07, 30.85, 32.59, 34.33, 36.15, 38.07]
Bitrate = [0.155, 0.194, 0.300, 0.443, 0.625, 0.880]

## CLIC Pro ##
PSNR = [31.84, 32.56, 34.13, 35.62, 37.13, 38.75]
Bitrate = [0.120, 0.151, 0.221, 0.328, 0.451, 0.649]

## Tecnick ##
PSNR = [32.06, 32.81, 34.35, 35.79, 37.23, 38.70]
Bitrate = [0.128, 0.158, 0.221, 0.318, 0.428, 0.605]

**Comment by Volodymyr233** [comment]
Thanks
