### ISSUE TITLE
LIC-TCM now available in TensorFlow2

### ISSUE THREAD

**Issue by Nikolai10** [jmliu206/LIC_TCM#15]
Dear @jmliu206, 

I am happy to share that LIC-TCM is now also available in TensorFlow 2:
https://github.com/Nikolai10/LIC-TCM

It would be great if you could include the TensorFlow implementation in your README :) Thanks!

**Comment by jmliu206** [comment]
Thank you for your interest in our work and for providing the TensorFlow2 implementation. 
I've added this implementation to the README. :)

**Comment by Nikolai10** [comment]
Great, thanks a lot! :)
