### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by Linkeyboard** [jmliu206/LIC_TCM#2]
Hi, my research interest focuses on end-to-end video coding. I would really appreciate it if you can provide the pretrained models of all bit-rate coding scenario. Thanks!

**Comment by jmliu206** [comment]
Thank you for your interest in our work. We want to note that the code on GitHub was rearranged by us, making it hard to load the previous checkpoint directly.
However, to obtain the other points, you can quickly retrieve their weights by finetuning directly and using the lambda=0.05 model as a pretrained model. 

You can try the following command to implement this finetune:

```
CUDA_VISIBLE_DEVICES='0' python -u ./train.py -d [path of training dataset] \
    --cuda --N 128 --lambda 0.0035 --epochs 20 --lr_epoch 16 18 \
    --save_path [path for checkpoint] --save \
    --checkpoint [path of the pretrained checkpoint (lambda=0.05)]
```
