### ISSUE TITLE
The detailed result

### ISSUE THREAD

**Issue by fengyurenpingsheng** [jmliu206/LIC_TCM#4]
Could you give the detailed results on Kodak, Tecnick and CLIC datasets? And the results aslo include small, middle and big models.

**Comment by jmliu206** [comment]
Thank you for your interest in our work. 
Please refer to:
https://github.com/jmliu206/LIC_TCM/blob/22cbdbfee0072648921b8a64d185aad4f84321c3/RD_data.md

**Comment by fengyurenpingsheng** [comment]
Thanks very much.
