### ISSUE TITLE
The result of reproduce code

### ISSUE THREAD

**Issue by fengyurenpingsheng** [jmliu206/LIC_TCM#5]

**Comment by fengyurenpingsheng** [comment]
Thank you for sharing your work, could you share how to train the results of MS-SSIM, and for PSNR results, the results of low bit rate are directly obtained from high bit rate finetuning, or the effect of direct training is better

**Comment by jmliu206** [comment]
I think you can finetune the high bit rate weights to get the low bit rate models. This will help the model converge faster.
